# Generated by Django 4.2 on 2023-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajaxtut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxvalue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ajaxvalue',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
